// <auto-generated />
namespace BookShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Admin_Duties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Admin_Duties));
        
        string IMigrationMetadata.Id
        {
            get { return "201808041551251_Admin_Duties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
